name: "CI"
on:
  pull_request:
jobs:

  tests-separate-datasource:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd $GITHUB_WORKSPACE
      - run: ./gradlew :examples:audit-test:check

  tests-same-datasource:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd $GITHUB_WORKSPACE
      - run: ./gradlew :examples:audit-test:check -Daudit-test.AuditTrail.datasource=DEFAULT

  tests-allow-update-outside-transaction:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd $GITHUB_WORKSPACE
      - run: ./gradlew :examples:audit-test-allow-update-outside-transaction:check